### ISSUE TITLE
Unable To See Candidate Information/Details

### ISSUE THREAD

**Issue by jtsai8** [KilimAnnejaro/CS506FinalProject#12]
The functionality to see candidate information, specifically their stances on different issues, does not exist. There is no option for the user to access this information. The user expects to see this information upon clicking the name of the candidate, but nothing happens.

**Severity:** Medium

**Reproduction Steps:**

Open the application on Android in Expo
Navigate to the “Ranking” page
There is no option to show information the candidate’s stances

**Comment by briannab16** [comment]
Added candidate info!
