### ISSUE TITLE
Navigating to signup page results in error with missing font

### ISSUE THREAD

**Issue by parlough** [KilimAnnejaro/CS506FinalProject#5]
At least on Android(9.0) using Expo, when you navigate to the signup page, you get an error where the font family, AmericanTypewriter, cannot be found. Possibly this font is not included on Android but is on iOS. The app still works, seeming to default back to a default system font, but that may cause your UI to look different across different problems and not as you expect. You can see the error on the bottom of the page.

**Severity:** Low, as app seems to fall back to system font

**Reproduction Steps:** 

1. Open the application on Android in Expo
2. Navigate to the “Signup” page
3. A red page should show up with the font error

**Suggestions:** 

Use a cross platform font, choose a fallback font, and/or include your intended one and load it asynchronously as the error suggests.

![screenshot_20190424-152118](https://user-images.githubusercontent.com/18372958/56693123-47b41080-66a9-11e9-8317-f8e8d88dd0be.jpg)

**Comment by KilimAnnejaro** [comment]
Hi, this problem is caused by one line in our code that is no longer active. Thanks!
